# Generated by Django 3.0.3 on 2020-03-03 21:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0010_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateTimeField(default=django.utils.timezone.now)),
                ('task', models.CharField(max_length=50, unique=True)),
                ('taskDetails', models.CharField(max_length=200, unique=True)),
                ('teamName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Team')),
            ],
            options={
                'unique_together': {('teamName', 'task')},
            },
        ),
    ]
