# Generated by Django 3.0.3 on 2020-03-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0013_timeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='task',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='taskDetails',
            field=models.CharField(max_length=200),
        ),
    ]
