# Generated by Django 3.0.3 on 2020-03-08 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0014_auto_20200305_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Role'),
        ),
        migrations.AlterUniqueTogether(
            name='teammember',
            unique_together={('teamName', 'role')},
        ),
    ]
