# Generated by Django 3.0.3 on 2020-05-05 23:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0015_auto_20200308_1747'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teammember',
            unique_together={('teamName', 'userName')},
        ),
    ]
