# Generated by Django 3.0.3 on 2020-05-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0016_auto_20200506_0455'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='grade',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
