# Generated by Django 3.0.3 on 2020-02-16 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0010_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200, unique=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('sentFrom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupFrom', to=settings.AUTH_USER_MODEL)),
                ('sentTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupTo', to='team.Team')),
            ],
        ),
    ]
