# Generated by Django 3.0.3 on 2020-02-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_directmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directmessage',
            name='message',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='message',
            field=models.CharField(max_length=200),
        ),
    ]
