# Generated by Django 3.0.3 on 2020-05-05 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0015_auto_20200308_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('grade', models.CharField(max_length=10, null=True)),
                ('approved', models.CharField(max_length=10, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Timeline')),
                ('teamName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Team')),
                ('uploadedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('name', 'uploadedBy', 'task')},
            },
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestedAt', models.DateTimeField(auto_now_add=True)),
                ('suggestion', models.CharField(max_length=2000)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.File')),
                ('suggestedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('name', 'suggestedBy', 'suggestedAt')},
            },
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approvedAt', models.DateTimeField(auto_now_add=True)),
                ('grade', models.CharField(max_length=10)),
                ('approvedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.File')),
            ],
            options={
                'unique_together': {('name', 'approvedBy')},
            },
        ),
    ]
