# Generated by Django 3.0.3 on 2020-05-05 20:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('upload', '0012_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggestion',
            old_name='name',
            new_name='file',
        ),
        migrations.AlterUniqueTogether(
            name='suggestion',
            unique_together={('file', 'suggestedBy', 'suggestedAt')},
        ),
    ]
