# Generated by Django 3.0.3 on 2020-05-05 20:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0013_auto_20200506_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='suggestedAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
