# Generated by Django 3.0.3 on 2020-05-05 21:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('upload', '0014_auto_20200506_0202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approval',
            old_name='name',
            new_name='file',
        ),
        migrations.AlterUniqueTogether(
            name='approval',
            unique_together={('file', 'approvedBy')},
        ),
    ]
