# Generated by Django 3.0.3 on 2020-05-08 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0015_auto_20200506_0232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='grade',
        ),
    ]
